//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_ERP_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Section()
        {
            this.SubjectRegistrations = new HashSet<SubjectRegistration>();
        }
    
        public int Section_ID { get; set; }
        public Nullable<int> SectionNumber { get; set; }
        public Nullable<int> Subject_ID { get; set; }
        public Nullable<int> SectionTime { get; set; }
        public string SectionDay { get; set; }
    
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectRegistration> SubjectRegistrations { get; set; }
    }
}
