//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_ERP_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.SubjectRegistrations = new HashSet<SubjectRegistration>();
        }
    
        public int Student_ID { get; set; }
        public string Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> NationalNum { get; set; }
        public Nullable<double> Grad { get; set; }
        public string Pic { get; set; }
        public int Status { get; set; }
        public string PersonalIdFile { get; set; }
        public string CertificateFile { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<int> Major_ID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Major Major { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectRegistration> SubjectRegistrations { get; set; }
    }
}
